FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive

RUN echo "Installing dependencies..." && \
	apt-get -y --no-install-recommends update && \
	apt-get -y --no-install-recommends upgrade && \
	apt-get install -y --no-install-recommends \
	build-essential \
	cmake \
	git \
	python-setuptools \
	python3.6 \
	python3-dev \
	python3-pip \
        python3-wheel \
        python3-venv \
	python3-setuptools \
	libopencv-dev 

#RUN apt-get -y update 

#RUN apt-get -y upgrade

#ENV FREELABEL_ROOT=/opt/freelabel
#WORKDIR $FREELABEL_ROOT


ENV HOME /home/freelabel-user
RUN useradd --create-home --home-dir $HOME freelabel-user \
	&& chown -R freelabel-user:freelabel-user $HOME

ENV FREELABEL_ROOT=$HOME/freelabel

USER freelabel-user

RUN mkdir $HOME/freelabel

WORKDIR $HOME/freelabel

#RUN echo "Create virtual environment..." && \
#	pip3 install --upgrade pip && pip3 install virtualenv

RUN echo "Create virtual environment..." && pip3 install virtualenv && pip3 install wheel

RUN echo "Downloading and building Freelabel..." && \
	git clone --branch main --depth 1 https://github.com/philadias/freelabel.git .

#WORKDIR $FREELABEL_ROOT/freelabel
WORKDIR $FREELABEL_ROOT/freelabel

RUN python3 -m pip install -r ../requirements.txt

RUN echo "Compile RGR..."

RUN python3 setup.py build_ext --inplace

WORKDIR $FREELABEL_ROOT
#WORKDIR $FREELABEL_ROOT
#WORKDIR $HOME

RUN echo "**** FOLLOW INSTRUCTIONS FROM README-docker.md TO START INTERFACE (printed below) *****" 

# RUN cat /opt/freelabel/docker/README-docker.md

#CMD ["python3"]
CMD ["python3 $FREELABEL_ROOT/manage.py runserver 0.0.0.0:9000"]
